### ISSUE TITLE
Plugin loads but does not modify any pasting behavior

### ISSUE THREAD

**Issue by no-simpler** [trystan2k/hyperterm-safepaste#1]
Cross-post of [this issue](https://github.com/zeit/hyper/issues/3567).

- **OS version and name**: macOS 10.14.4
- **Hyper.app version**: 2.1.2 / 3.0.0-canary.8
- **Contents of .hyper.js**: [link](https://gist.github.com/no-simpler/7bf973791cb4281293d13fe8a0b23ab0)
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
This plugin does not work, although it loads. That is, pasting behavior is not modified in any way, e.g., trailing newlines are not removed.

**On `stable`**, dev tools say:

```
Plugin hyperterm-safepaste (1.0.5) loaded.
```

**On `canary`**, dev tools say:

```
[Notification] Plugin load error: "hyperterm-safepaste" failed to load in the renderer process. Check Developer Tools for details.
bundle.js:1 EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'".
```

**Comment by zsol** [comment]
Sorry, @no-simpler, I no longer maintain this plugin as I stopped using Hyper a while ago. If you'd like to take over, let me know

**Comment by no-simpler** [comment]
> Sorry, @no-simpler, I no longer maintain this plugin as I stopped using Hyper a while ago. If you'd like to take over, let me know

No worries, @zsol, thanks for the initial contribution.

Just out of curiosity, which terminal did you move toward?

**Comment by zsol** [comment]
I'm using https://github.com/kovidgoyal/kitty nowadays :)

**Comment by no-simpler** [comment]
Thanks. All the best!
