### ISSUE TITLE
Esc doesn't cancel the paste.

### ISSUE THREAD

**Issue by shreyas-srinivas** [trystan2k/hyperterm-safepaste#16]
Nothing happens when the ESC key pressed while in the paste mode. 

Hyper version 3.0.2
Windows 10

**Comment by trystan2k** [comment]
Hi @shreyas-srinivas,

I have just opened the PR to fix this issue. 

Hopefully the next version will be release soon.

Thanks !

**Comment by shreyas-srinivas** [comment]
Thanks @trystan2k !!

**Comment by trystan2k** [comment]
Hi @shreyas-srinivas,

Sorry for the delay, but this fix is finally published in version 3.0.4.

You just need to update it in your Hyper to be able to use it.

Please let me know if you find any issue !

Regards!

**Comment by shreyas-srinivas** [comment]
Thanks for the update @trystan2k 🙂
