### ISSUE TITLE
Fails with the new Hyper v3

### ISSUE THREAD

**Issue by hector** [trystan2k/hyperterm-safepaste#2]
The following error appears when opening Hyper:

"hyperterm-safepaste" failed to load in the renderer process.

**Comment by ffuubarbuzz** [comment]
More detailed error message:

> EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'".

**Comment by FMGordillo** [comment]
Bump bump bump

**Comment by zsol** [comment]
I no longer maintain this plugin as I stopped using Hyper a while ago. If you'd like to take over, let me know :)

**Comment by trystan2k** [comment]
Hi.

I just merged a change that make hyperterm-safepaste compatible with Hyper 3.x 

zsol will publish it on NPM soon. 

I performed a lot of tests on my machine (macos), so if you guys can do more tests on your setu and let us know if you find any issue, that would be awnsome!

We will close this issue once it is published.

Thank you !

**Comment by zsol** [comment]
published as `2.0.0`

Have fun!
