### ISSUE TITLE
Does this work on Windows?

### ISSUE THREAD

**Issue by fatpowaranga** [trystan2k/hyperterm-safepaste#21]
I've tried to get this working on my Windows 11, and no matter what I do neither the single line or multi line works. Any ideas on what I could try or is this plugin maybe not usable for Windows?

**Comment by trystan2k** [comment]
Hi @fatpowaranga,

Yes, it should work in Windows without problem.
I just tested in a new installation in Windows 11, and it worked without problems:
![image](https://user-images.githubusercontent.com/447294/139036446-0c002605-9629-49b1-9f24-fac0012a3169.png)

Did you have it added in the plugins list in Hyper configuration as follows:
![image](https://user-images.githubusercontent.com/447294/139036643-b4896f8e-0b20-4b3d-947b-73c61953a58a.png)

Did you try to restart Hyper after added the plugin ?

Could you have another plugin that could be conflicting with hyperterm-safepaste ? Do you mind sharing your hyper configuration file ?

Thanks !
